sudo: false
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "6.11"
  - "4.1"
  - "4.0"
  - "0.12"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - "git config --global user.email 'johndoe@example.com'"
  - "git config --global user.name 'John Doe'"
script: npm run travis
